name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust:
    name: Rust tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/blockchain-node
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src/blockchain-node -> target

      - name: Run tests
        run: cargo test --all --locked --verbose

  go:
    name: Go tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/contrib-oracle
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Run tests
        run: go test ./... -v

  frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Run tests (if present)
        env:
          CI: true
        run: npm run test --if-present -- --watchAll=false
